# Generated by Django 4.0.4 on 2022-04-27 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_remove_team_members_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
